name: Sync to GitLab
on:
  push:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to GitLab
        env:
          GITLAB_URL: https://XiaoYuan151:${{ secrets.GITLAB_TOKEN }}@gitlab.com/XiaoYuan151/home.git
        run: |
          git remote add gitlab "${GITLAB_URL}"
          git push gitlab --prune --all
